### PR TITLE
Add a delete type

### PR DESCRIPTION
**Pull request by wasabigeek**
@JungWinter for your consideration - will add documentation if it's ok!

### CODE REVIEW

**Review by winterjung — APPROVED** [review]
lgtm! thanks for your contribution. after documentation, feel free to ping me :)

**Review by winterjung — APPROVED** [review]
👍

**Comment by winterjung** [comment]
I'll fix the broken integration ci

**Comment by wasabigeek** [comment]
Dang sorry 🙏

**Pull request merged**
